#!/bin/sh
set -eux

. ./mock_shelduck.sh
shelduck base.sh
shelduck string.sh
shelduck assert.sh

main() {
	printf '<%s> ' "$@"
	#. "./$1"
}



shelduck ./entry_point.sh
echo "DEBUG: ${0}"
echo "DEBUG: ${0##*/}"