

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: ci
        run: sh ./run ci
        env:
          GH_TOKEN: ${{ github.token }}